management.endpoints.web.exposure.include: "*"

spring.profiles.active: dev

#---

# EXAMPLE COMENT
#
#spring:
#  profiles: dev
#server:
#  port: 9080

#---

#spring:
#  profiles: prod  
#server:
#  port: 9080


spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
   console.enabled: true
   console.path: /h2-console 
        